apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-webhook-service
  namespace: kyma-system
  labels:
    name: api-gateway-webhook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-gateway-webhook-service
  template:
    metadata:
      labels:
        name: api-gateway-webhook-service
        sidecar.istio.io/inject: "false"
    spec:
      containers:
       - name: api-gateway-webhook-service
         image: docker.io/videlov/api-gateway-webhook-service:0.0.1
         command:
         - /api-gateway-webhook-service
         ports:
         - containerPort: 9443
           protocol: TCP
         volumeMounts:
           - name: webhook-certs
             mountPath: /etc/webhook/certs
             readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: api-gateway-webhook-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-webhook-service
  namespace: kyma-system
spec:
  ports:
  - port: 9443
    protocol: TCP
  selector:
     name: api-gateway-webhook-service
  type: ClusterIP
