apiVersion: v1
kind: Service
metadata:
  name: crd-conversion-webhook
  namespace: crd-conversion-webhook
spec:
  ports:
  - name: tls
    port: 443
    targetPort: tls
  selector:
     name: crd-conversion-webhook
  type: ClusterIP
